# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 800)
        Form.setStyleSheet("background-color: rgb(17, 17, 17);")
        self.coords1 = QtWidgets.QLineEdit(Form)
        self.coords1.setGeometry(QtCore.QRect(10, 80, 581, 61))
        self.coords1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Bahnschrift SemiLight Condensed\";\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.coords1.setObjectName("coords1")
        self.coords2 = QtWidgets.QLineEdit(Form)
        self.coords2.setGeometry(QtCore.QRect(10, 10, 581, 61))
        self.coords2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"Bahnschrift SemiLight Condensed\";\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.coords2.setObjectName("coords2")
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(220, 160, 150, 150))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight Condensed")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button.setFont(font)
        self.button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 40pt \"Bahnschrift SemiLight Condensed\";\n"
"border: 2px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.button.setObjectName("button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.coords1.setText(_translate("Form", " Координаты по Y"))
        self.coords2.setText(_translate("Form", " Координаты по X"))
        self.button.setText(_translate("Form", "SEARCH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
